### PR TITLE
	[IMP] Upgrade to new quality tools

### PR DESCRIPTION
**Pull request by lasley**
Depends LasLabs/docker-quality-tools#1

### CODE REVIEW

**Review by tedsalmon — APPROVED** [review]
👍  LGTM!

**Comment by lasley** [comment]
Switched the DQT branch to master in travis and pushed. If build goes 🍏  we're good to merge then

**Comment by tedsalmon** [comment]
Merged as it went 🍏  :D

**Comment by lasley** [comment]
In the words of Tech - Cha!

**Pull request merged**
